# Build settings
gems:
  - jemoji
  - jekyll-paginate
  
# Site settings
title: "Team Ice Breaker"
description: > # this means to ignore newlines until "email:"
   Colin Ferris, 
   Steven Greenberg, 
   Wesley Wigham, 
   Zachary Calfin

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/tiger.jpg"
# blog cover
cover: "/assets/images/bg.jpg"

name: 'Team Ice Breaker'
author: 'Team Ice Breaker'
author_image: "/assets/images/tiger.jpg"

paginate:	5

url: "http://icebreaker.se.rit.edu" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

nav_item:
  - url: info
    desc: Project Info
  - url: https://docs.google.com/document/d/11ug407kmWp2jNfbNXkVK_eDwPAEn_tB3iwnlyoBGhAU/pub
    desc: Time Tracking Reports
    
# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/team-ice-breaker
    desc:	Team GitHub
    share_url:
    share_title:
    share_link: