# Build settings
gems:
  - jemoji
  - jekyll-paginate
  
# Site settings
title: "Team Ice Breaker"
description: > # this means to ignore newlines until "email:"
   Colin Ferris, 
   Steven Greenberg, 
   Wesley Wigham, 
   Zachary Calfin

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/tiger.jpg"
# blog cover
cover: "/assets/images/bg.jpg"

name: 'Team Ice Breaker'
author: 'Team Ice Breaker'
author_image: "/assets/images/tiger.jpg"

paginate:	5

url: "http://icebreaker.se.rit.edu" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

nav_item:
  - url: info
    desc: Project Info
  - url: https://docs.google.com/spreadsheets/d/1w_F78z7NpLgWol0Lwgcyw0X_5e_P_L_UdNovVzr1Frs/pubhtml
    desc: Time Tracking Reports
  - url: http://glimpseio.github.io/glacier
    desc: Travis Output
  - url: deliverables
    desc: Deliverables
    
# social icons and sharing options
social:

  - icon:	github
    url:	https://github.com/glimpseio/glacier
    desc:	Glacier
    share_url:
    share_title:
    share_link: